name: Build image

on:
  push:
    branches: [ unstable ]
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: hujw77/ssz
          path: ssz

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}
      - uses: benjlevesque/short-sha@v1.2

      - name: Prepare deps
        working-directory: ssz
        run: |
          set -xe
          yarn
          yarn build

      - name: Build package
        run: |
          set -xe
          yarn
          rm -rf node_modules/@chainsafe/persistent-merkle-tree
          mv ssz/packages/persistent-merkle-tree node_modules/@chainsafe
          yarn build
          rm .dockerignore # we build image from github action. so we don't need this file
          ls -la

      - name: Build and publish image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}:sha-${{ env.SHA }}
          file: hack.Dockerfile


