name: Publish stg

on:
  push:
    branches: [ fox ]

jobs:
  docker:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    if: needs.tag.outputs.is_rc == 'true'
    steps:
      - uses: actions/checkout@v2
      - run: scripts/await-release.sh ${{ needs.tag.outputs.tag }} rc 900
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:sha-${{ env.SHA }}
          file: docker/from_source.Dockerfile

      # - name: Build and push
      #   run: |
      #     docker buildx build \
      #       --push \
      #       --file docker/from_source.Dockerfile \
      #       --tag chainsafe/lodestar:rc \
      #       --tag chainsafe/lodestar:${{ needs.tag.outputs.tag }} \
      #       --platform linux/amd64 \
      #       --build-arg VERSION=${{ needs.tag.outputs.tag }} \
      #       .
